// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq1R63kR9i5f3_erJ26uYyzR4MfA2eYrk',
    appId: '1:1026172948892:web:d2937de4ff1ed9fe637859',
    messagingSenderId: '1026172948892',
    projectId: 'anti-theft-detection',
    authDomain: 'anti-theft-detection.firebaseapp.com',
    storageBucket: 'anti-theft-detection.appspot.com',
    measurementId: 'G-19RHD73XFR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjfqKEQuIUxPlCmoTQFPIzDbiCEq9_ROg',
    appId: '1:1026172948892:android:383f6cf8e183aae2637859',
    messagingSenderId: '1026172948892',
    projectId: 'anti-theft-detection',
    storageBucket: 'anti-theft-detection.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADzCxvbpmkx55irYTo0I17JIPKttz4Sgc',
    appId: '1:1026172948892:ios:163f16a48ceb8a0a637859',
    messagingSenderId: '1026172948892',
    projectId: 'anti-theft-detection',
    storageBucket: 'anti-theft-detection.appspot.com',
    iosBundleId: 'com.example.antiTheftDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADzCxvbpmkx55irYTo0I17JIPKttz4Sgc',
    appId: '1:1026172948892:ios:2e96bede0592ab67637859',
    messagingSenderId: '1026172948892',
    projectId: 'anti-theft-detection',
    storageBucket: 'anti-theft-detection.appspot.com',
    iosBundleId: 'com.example.antiTheftDemo.RunnerTests',
  );
}
